// Curated list of common ISO 4217 fiat currencies.
// Used when adding currencies to a workspace.
export const FIAT_CURRENCIES: ReadonlyArray<{ code: string; name: string }> = [
	{ code: "USD", name: "US Dollar" },
	{ code: "EUR", name: "Euro" },
	{ code: "GBP", name: "British Pound" },
	{ code: "JPY", name: "Japanese Yen" },
	{ code: "AUD", name: "Australian Dollar" },
	{ code: "CAD", name: "Canadian Dollar" },
	{ code: "CHF", name: "Swiss Franc" },
	{ code: "CNY", name: "Chinese Yuan" },
	{ code: "HKD", name: "Hong Kong Dollar" },
	{ code: "SGD", name: "Singapore Dollar" },
	{ code: "SEK", name: "Swedish Krona" },
	{ code: "NOK", name: "Norwegian Krone" },
	{ code: "DKK", name: "Danish Krone" },
	{ code: "NZD", name: "New Zealand Dollar" },
	{ code: "MXN", name: "Mexican Peso" },
	{ code: "BRL", name: "Brazilian Real" },
	{ code: "INR", name: "Indian Rupee" },
	{ code: "RUB", name: "Russian Ruble" },
	{ code: "ZAR", name: "South African Rand" },
	{ code: "TRY", name: "Turkish Lira" },
	{ code: "AED", name: "UAE Dirham" },
	{ code: "SAR", name: "Saudi Riyal" },
	{ code: "KRW", name: "South Korean Won" },
	{ code: "IDR", name: "Indonesian Rupiah" },
	{ code: "MYR", name: "Malaysian Ringgit" },
	{ code: "THB", name: "Thai Baht" },
	{ code: "PHP", name: "Philippine Peso" },
	{ code: "VND", name: "Vietnamese Dong" },
	{ code: "CZK", name: "Czech Koruna" },
	{ code: "PLN", name: "Polish Zloty" },
	{ code: "HUF", name: "Hungarian Forint" },
	{ code: "ILS", name: "Israeli Shekel" },
	{ code: "CLP", name: "Chilean Peso" },
	{ code: "COP", name: "Colombian Peso" },
	{ code: "ARS", name: "Argentine Peso" },
	{ code: "PKR", name: "Pakistani Rupee" },
	{ code: "EGP", name: "Egyptian Pound" },
	{ code: "NGN", name: "Nigerian Naira" },
	{ code: "KES", name: "Kenyan Shilling" },
	{ code: "GHS", name: "Ghanaian Cedi" },
	{ code: "PHP", name: "Philippine Peso" },
	{ code: "TWD", name: "Taiwan Dollar" },
	{ code: "BDT", name: "Bangladeshi Taka" },
] as const;

export function getCurrencyName(code: string): string {
	return FIAT_CURRENCIES.find((c) => c.code === code)?.name ?? code;
}
